# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuser',
            name='photo',
            field=models.ImageField(default='/media/users/photos/default.png', upload_to='users/photos'),
        ),
    ]
