# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReviewer',
            fields=[
                ('activity_reviewer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPlan',
            fields=[
                ('review_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_item_start', models.DateTimeField(verbose_name='Start time')),
                ('plan_item_end', models.DateTimeField(verbose_name='End time')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('submit_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('programming_language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProgrammingLanguage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('submit_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFileType',
            fields=[
                ('submit_file_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sumbmit_file_type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='submitfile',
            name='submit_file_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.SubmitFileType'),
        ),
        migrations.AddField(
            model_name='submitfile',
            name='submit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Submit'),
        ),
        migrations.AddField(
            model_name='reviewplan',
            name='submit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Submit'),
        ),
        migrations.AddField(
            model_name='activityreviewer',
            name='submit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Submit'),
        ),
        migrations.AddField(
            model_name='activityreviewer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
