# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('submit_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProgrammingLanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('submit_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=256)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Submit')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFileType',
            fields=[
                ('submit_file_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sumbmit_file_type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitReviewer',
            fields=[
                ('submit_reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Submit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitReviewPlan',
            fields=[
                ('submit_review_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_item_start', models.DateTimeField(verbose_name='Start time')),
                ('plan_item_end', models.DateTimeField(verbose_name='End time')),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Submit')),
            ],
        ),
        migrations.AddField(
            model_name='submitfile',
            name='submit_file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.SubmitFileType'),
        ),
    ]
