# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField()),
                ('comment_time', models.DateTimeField()),
                ('comment_text', models.TextField(max_length=4096)),
                ('agree_count', models.IntegerField()),
                ('reply_of_comment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('comment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.CommentType'),
        ),
    ]
